openapi: "3.0.0"
info:
  version: 1.3.2
  title: OpenAPE
  license:
    name: Apache2.0
servers:
  - url: http://openape.gpii.eu
  
paths:
  /myid:
    get:
      responses:
        200:
          description: returns user Id
          content:
            text/plain:
              schema:
                type: string
  /openape/groups:
    get:
      description: Returns a List to all available OpenAPE groups
      tags:
        - OpenAPE
        - groups
      responses:
        200:
          description: A list of all available groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupList"
    post:
      summary: Creates a new OpenAPE Resource group
      tags:
        - OpenAPE
        - Groups
      security:
        - OAuth2:
          - user
          - admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schema/GroupRequest"
      responses:
        201:
          description: Id of created group
          content:
            application/json:                 
              schema:
                type: string        
  /api/user-contexts:  
    get:
      summary: List of URIs to all accessible user contexts
      operationId: getUserContextList
      tags:
        - Usercontext
        - userContextList
      security:
        - OAuth2:
          - default
          - user
          - admin
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A list of URIs to user contexts
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/UserContextList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new user context
      operationId: createUserContext
      tags:
        - UserContext
      security:
        - OAuth2:
          - user
          - admin
      responses:
        201:
          description: user context successfully created
          content:
            text/plain:
              schema:
                type: string
        400:
          description: unauthorized
          content:
            text/plain:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/user-contexts/{userContextId}:
    get:
      summary: Info for a specific user context
      operationId: getUserContextById
      tags:
        - UserContext
      parameters:
        - name: userContextId
          in: path
          required: true
          description: The id of the user context to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserContext"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      description: update the speciified user context
      tags:
        - UserContext
        - update
      security:
        - OAuth2:
          - user
          - admin
      parameters:
        - name: userContextId
          in: path
          required: true
          description: The id of the user context to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserContext"              
      responses:
        200:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: delete the speciified user context
      security:
        - OAuth2:
          - user
          - admin
      
      parameters:
        - name: userContextId
          in: path
          required: true
          description: The id of the user context to delete
          schema:
            type: string
      responses:
        200:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: returns Id of created user
          content:
            text/plain:
              schema:
                type: string
  /users/{userId}/password:
    put:
      summary: can be used to change pasword
      tags:
        - OpenAPE
        - User
      security:
        - OAuth2:
          - admin
          - user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: successful change of password
          content:
            text/plain:
              schema:
                type: string
            
        
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    GroupList:
      type: string
    GroupRequest:
      type: string
    User:
      type: application/json
      description: Representation of  an OpenAPE user

    User-context:
      type: application/json
      description: user context as described in ISO 24752-8
    UserContextList:
      type: application/json
      description: user context list object as described in ISO 24752-8
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: http://openape.gpii.eu/token
          scopes:
            default: grants access to all public contexts 
            user: grants access to private contexts 
            admin: Grants access to admin operations
            read: grants read access to resources
         