package org.openape.ui.velocity.molecules;

import org.openape.ui.velocity.atoms.Atom_1_navigationLinks;

public class Molecule_5_dataTable {
	public String generateSubNavigation(){
		
		String tableContent = "";
		
		tableContent =  "<tr>"
				+ "<td>Waldemar</td>"
				+ "<td>594d4a1804bac11a8c68c765</td>"
				+ "<td>wjaufmann@gmx.de</td>"
				+ "<td>admin</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"
				+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>"+ "<tr>"
				+ "<td>Lukas</td>"
				+ "<td>594d4ae204bac133b0c22e1c</td>"
				+ "<td>lukas@gmx.de</td>"
				+ "<td>user</td>"
				+ "<td>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-edit'></div> Edit </button>"
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-trash'></div> Delete </button> "
				+ "<button class='btn btn-md btn-default'><div class='glyphicon glyphicon-copy'></div> Copy to clipboard  </button> </td></tr>";
		
		
		return tableContent;
	}
}

